### ISSUE TITLE
Multithreading issue

### ISSUE THREAD

**Issue by Cloud299** [ina-foss/inaSpeechSegmenter#10]
The code works well when run iteratively. However, for applications that require multithreading (CPU) and segmenting multiples files in parallel, there is a lock on the process. Is there way to fix this ? In other words, is there a way to load the model once and use it on multiple threads to segment several files at once?
I think this has to do with the tensorflow backend.

**Comment by DavidDoukhan** [comment]
The method I used to segment multiple file in parallel consisted to use a client/server architecture implemented with Pyro.
The server distribute url of file to process. Clients ask the server for a job one they have finished.
Each client should be lauched using environment variables to be used by tensorflow, shuch as the identifier of the GPU to be used (CUDA_VISIBLE_DEVICES), or the number of CPU threads to be used for CPU implementation (i don't remember the name of this environment variable).

The other method would be to import inaSpeechSegmenter inside each thread, instead of doing it before launching the threads
