### ISSUE TITLE
Error in loading saved optimizer

### ISSUE THREAD

**Issue by premingiet** [ina-foss/inaSpeechSegmenter#14]
i am using windows 10, and when i ran the command, it works fine and then gives me this error

"Error in loading the saved optimizer state. As a result, your model is starting with a freshly initialized optimizer."

It segments the audio but its incorrect, i mean i am able to get csv file but the detection is wrong, even with english audio with no background noise or overlap. why i get this error ?

**Comment by DavidDoukhan** [comment]
The saved optimizer state is not necessary for using the trained model.
It is only used when trying to retrain the model using new data.

Concerning the incorrect segmentation you're reporting:
Could you send me the example audio which produce wrong segmentation on your computer, together with inaspeechsegmenter's csv output?
This would allow me to see if the errors are due to your installation, or to the sofrware itself.

Kind regards,

**Comment by DavidDoukhan** [comment]
I've uploaded new versions of the trained models.
These are now saved without optimizer's state.
As a consequence, the warning message you reported is no longer reported by the program.

Kind regards,
