### ISSUE TITLE
Matplotlib TypeError: use() got an unexpected keyword argument 'warn'

### ISSUE THREAD

**Issue by vancdk** [ina-foss/inaSpeechSegmenter#54]
## System information
- Matplotlib version: 3.3.2
- Python version: 3.8

## Expected Behavior
A successful analysis of the inputted media:
`1/1 [('/Users/vanessachaddouk/Desktop/Voice_Gender_Output/musanmix_test-voice.csv', 0, 'ok')]`

## Current Behavior
When I input a media to analyze, inaSpeechSegmenter returns this error:
`TypeError: use() got an unexpected keyword argument 'warn'`

## Steps to Reproduce

1. Install inaSpeechSegmenter with the latest version of matplotlib (currently 3.3.2)
2. Input a media to analyse.

## Additional infos
A quick fix is to install an earlier version of matplotlib.
In my case I set it to 3.2 in order to use the current code:
`pip install matplotlib==3.2`

For reference, this is the full traceback:
![image](https://user-images.githubusercontent.com/74259267/108698531-849af980-7504-11eb-85f3-e41ef4dcb1b9.png)

**Comment by DavidDoukhan** [comment]
Dear @vancdk ,

Thanks for this message.

I did a test using Python 3.8.5 and the latest version of matplotlib (installed by default) without experiencing any problem.

```
(inaSpeechSegEnv) ddoukhan@lucrate-titan:/tmp$ python --version
Python 3.8.5
(inaSpeechSegEnv) ddoukhan@lucrate-titan:/tmp$ pip freeze|grep matplotlib
matplotlib==3.3.4
```

We may need more details on your system's configuration (OS) and the steps you used to install inaspeechsementer in order to reproduce this issue.

Kind regards,
