### ISSUE TITLE
Getting "terminated: Application failed to start: not available" for longer audio files

### ISSUE THREAD

**Issue by suraj143rosy** [ina-foss/inaSpeechSegmenter#67]
When i ran this for a 30 mins audio file , I am getting the below error.
"terminated: Application failed to start: not available" .

Can you please check and update what this is related to?

**Comment by DavidDoukhan** [comment]
Dear @suraj143rosy ,
Could you provide us more details on your issue, using the issue template bellow ?
I would suggest to pay a particular attention to the amount of RAM available in your host, and to the results of the unit tests.
Kind regards,

Please fill out this template for a bug report.

Make sure you ran the unit tests before submitting an issue and tell us if and where they fail.




## System information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow version:
- Python version:
- Running on GPU or CPU:
- output of command nvidia-smi (if GPU is used)
- CUDA/cuDNN version (if GPU is used):
- Using Docker: 

## Expected Behavior


## Current Behavior




## Steps to Reproduce


1.
2.
3.
4.


## Additional infos

**Comment by suraj143rosy** [comment]
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Cloud run
TensorFlow version: 2.7
Python version: 3.6.9
Running on CPU

Expected behavior:
It should work for larger audio files of duration more than 30 mins. 
Current Behavior:
It is working for smaller files, but not for larger files. It is breaking at this line of the code only for larger audio files.
mag = numpy.fft.rfft(ahan, n_fft, axis=-1)

**Comment by DavidDoukhan** [comment]
Hi,

In order to help you, I would need to know the amount of RAM available on your host. I would also suggest you to monitor the RAM usage of the program when you launch it on large files.

inaSpeechSegmenter has beeen often used on recordings of several hours. It may crash if a very limited amout of RAM is available....

**Comment by suraj143rosy** [comment]
The ram available on Cloud run is around 8 gb. Also the ram usage reaches max till 80%. Should i try on higher RAM?

**Comment by DavidDoukhan** [comment]
This would be my first advice ! I usually run it using 32 Gb RAM machines.

**Comment by suraj143rosy** [comment]
Okay. Thank you. It worked on 16 gb RAM devices.

**Comment by DavidDoukhan** [comment]
cool!
