### ISSUE TITLE
How to run on GPU

### ISSUE THREAD

**Issue by comx3i** [ina-foss/inaSpeechSegmenter#75]
How can we run Segmenter on GPU?

**Comment by DavidDoukhan** [comment]
Dear @comx3i ,

In order to be able to provide you a relevant answer, I would need that you fill the issue template : 
https://github.com/ina-foss/inaSpeechSegmenter/blob/master/.github/ISSUE_TEMPLATE.md

Basically, if your GPU drivers, CUDA and CUDNN are correctly installed, then the sotfware should use the GPU without any particular intervention from your side.
